#!/bin/bash

echo " install dependencies"

apt-get install -qq -y --no-install-recommends git
apt-get install -qq -y --no-install-recommends cmake
apt-get install -qq -y --no-install-recommends postgresql-server-dev-15

# cd /tmp
# git clone --branch v0.4.4 https://github.com/pgvector/pgvector.git
# cd pgvector
# make
# make install # may need sudo