#!/bin/bash



# echo "shared_preload_libraries = '$ext'" >> /tmp/postgresql.conf.sample
# sudo dd if=/tmp/postgresql.conf.sample of=$PHOENIX_HOME/share/postgresql/postgresql.conf.sample oflag=append conv=notrunc
# tail $PHOENIX_HOME/share/postgresql/postgresql.conf.sample
rm -r -f $PGDATA
initdb -D ${PGDATA}/ -E "UTF8" --auth=trust --auth-host=trust --auth-local=trust
