FROM dep:latest

# ARG DEBIAN_FRONTEND=noninteractive
ARG cnt_user=none
ENV cnt_user=$cnt_user

WORKDIR $cnt_user

RUN mkdir -p code
ADD volume/phoenix  code/phoenix
ADD volume/babelfish    code/babelfish
ADD volume/postgresql   code/postgresql
ADD volume/telnet_srv   code/telnet_srv
ADD volume/phoenix_srv_av   code/phoenix_srv_av

RUN  chown -R $cnt_user:$cnt_user  code
USER ${cnt_user}


ENV PHOENIX_HOME=/usr
ENV PGDATA=/$cnt_user/pgdata
ENV LANG=en_US.utf8
ENV LC_ALL="C.UTF-8"

#shorthand for utilities
ENV PATH=/$cnt_user/code/phoenix/dkr/scripts:$PATH


# make main  PG
RUN  /$cnt_user/code/phoenix/dkr/scripts/make_pg
# make telnet extension and add config files
RUN  /$cnt_user/code/phoenix/dkr/scripts/make_tl
# make phn extension and add config files
RUN  /$cnt_user/code/phoenix/dkr/scripts/make_phn

# add  logging control
RUN sudo dd if=/$cnt_user/code/phoenix/dkr/scripts/postgres_log.conf of=$PHOENIX_HOME/share/postgresql/postgresql.conf.sample oflag=append conv=notrunc
RUN tail -n 10 $PHOENIX_HOME/share/postgresql/postgresql.conf.sample


ENTRYPOINT ["sleep", "36000"]